<?php use Roster\Model\Roster; ?>

<?php $table_id = strval(random_int(0, 999999)); ?>
<script type="text/javascript">
function searchTable() {
    var input, filter, table, tr, td, i, z, negate, txtValue;
    input = document.getElementById("search");
    filter = input.value.toUpperCase();
    table = document.getElementById("<?=$table_id?>");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
		z = 0;
		
		do {
			td = tr[i].getElementsByTagName("td")[z];
			if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                	tr[i].style.display = "";
                	break;
                } else {
                    tr[i].style.display = "none";
                }
            }    
            z++;
		} while (z <= 3);
    }
    // Only queries the last column
}

function sortTable(n) {
  var loader, table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("<?=$table_id?>");
  loader = document.getElementById("loader");
  loader.style.display = "block";
  switching = true;
  //Set the sorting direction to ascending:
  dir = "asc"; 
  /*Make a loop that will continue until
  no switching has been done:*/
  while (switching) {
    //start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /*Loop through all table rows (except the
    first, which contains table headers):*/
    for (i = 1; i < (rows.length - 1); i++) {
      //start by saying there should be no switching:
      shouldSwitch = false;
      /*Get the two elements you want to compare,
      one from current row and one from the next:*/
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /*check if the two rows should switch place,
      based on the direction, asc or desc:*/
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch= true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /*If a switch has been marked, make the switch
      and mark that a switch has been done:*/
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      //Each time a switch is done, increase this count by 1:
      switchcount ++;      
    } else {
      /*If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again.*/
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
  loader.style.display = "none";
}
</script>

<style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>

<div class="card mb-4">
	<?php if (isset($this->title)) : ?>
	<div class="card-header d-flex justify-content-between">
		<div>
			<b><?=$this->title?></b>
		</div>
		<?php if ($this->search) : ?>
		<div><input type="text" id="search" onkeyup="searchTable()" placeholder="Search ..." title="Search..."></div>
		<?php endif; ?>
		
		<?php if ($this->form) : ?>
		<div>
			<a href="" class="btn btn-primary btn-rounded" data-bs-toggle="modal" data-bs-target="#modal-<?=$this->form['name']?>"><?=$this->form['title']?></a>
		</div>
		<?php endif; ?>
		<?php if (isset($this->help)) : ?>
		<div>
			<button type="button" class="btn btn-primary btn-sm" data-bs-toggle="popover" data-bs-title="<?=$this->help['TITLE']?>" data-bs-content="<?=$this->help['TEXT']?>"><?=$this->help($help['ICON'])?></button>
		</div>
		<?php endif; ?>
	</div>
	<?php endif; ?>


	<?php 
	$classes = [
	    Roster::INTERESTED_STATUS => 'text-success',
	    Roster::NOTINTERESTED_STATUS => 'text-danger',
	    Roster::ACTIVE_STATUS => 'text-primary',
	    Roster::INACTIVE_STATUS => 'text-secondary',
	];
	
	?>
	<div class="loader" id="loader" style="display: none;"></div>
	<div class="card-body">
		<?php if (sizeof($data) === 0) { echo "No Records Retrieved."; } else { ?>
    	<table class="table table-striped" id="<?=$table_id?>">
        	<thead>
        		<tr>
        	<?php 
        	   $i=0;
        	   $header = array_keys(array_values($this->data)[0]); 
        	   foreach ($header as $key) {
        	       if (strpos($key, $this->primary_key) === 0 || $key == 'STATUS') { continue; }
        	       echo "<th onclick='sortTable($i)' style='cursor: pointer;'>$key</th>";
        	       $i++;
        	   }
           ?>
           			<th></th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach ($this->data as $record) : ?>
        		<tr>
        			<?php foreach ($record as $key => $value) : ?>
        				<?php if (strpos($key, $this->primary_key) === 0 || $key == 'STATUS') { continue; } ?>
        				<td><?php echo "<span class='" . $classes[$record['STATUS']] . "'>$value</span>"; ?></td>
        			<?php endforeach; ?>
        			<td class="float-right">
        			<?php if (sizeof($this->params)) : ?>
                        <div class="dropdown">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            	<i class="fas fa-bars"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <?php 
                            foreach ($this->params as $item) {
                                $href = $this->url($item['route'], ['action' => $item['action'], strtolower($this->primary_key) => $record[$item['key']]], null, true);
                                echo "<a class='dropdown-item' href='$href'>" . $item['label'] . "</a>";
                            }
                            ?>
                            </div>
                        </div>
                    <?php endif; ?>
        			</td>
        		</tr>
        		<?php endforeach; ?>
        	</tbody>
    	</table>
    	<?php } ?>
	</div>
</div>