<div class="modal fade" id="job_type_create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
    		<div class="card mb-4">
            	<div class="card-header d-flex justify-content-between">
            		<div>
            			<b>Add Job Type</b>
            		</div>
            	</div>
            	<div class="card-body">
            		<?php 
            		$form->setAttribute('action', $this->url('job/type', ['action' => 'create']));
            		
            		$form->prepare();
            		
            		echo $this->form()->openTag($form);
            		echo $this->formCollection($form);
            		echo $this->form()->closeTag($form);
            		?>
				</div>
			</div>
		</div>
	</div>
</div>