<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Welcome to<br>Private Duty Hiring Application</h1>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Terms of Service</h2>
            <div class="card-body">
                <p>
                    
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="<?=$this->url('application', ['action' => 'terms'])?>">Terms of Service &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Privacy Policy</h2>
            <div class="card-body">
                <p>
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="<?=$this->url('application', ['action' => 'privacy'])?>">
                    Privacy Policy &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Help &amp; Support</h2>
            <div class="card-body">
                <p>
                    If you need any help or support while developing with Laminas,
                    you may reach us via <a href="https://laminas.dev/chat">chat</a> or
                    <a href="https://discourse.laminas.dev">forum</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding any release.
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="https://laminas.dev/chat" target="_blank">Ping us on chat &raquo;</a>
            </div>
        </div>
    </div>
</div>
